### ISSUE TITLE
List

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/Capstone-Project-Lecker-Map#3]
## Title
List of Restaurants

## Value Proposition
- As a user
- I want to have a list of Restaurants 
- in order to read them

## Description

![Image](https://user-images.githubusercontent.com/123362292/227465348-81e4acce-0a31-44fc-9482-6ac1252a28a1.png)

## Acceptance criteria
- [ ] The "Restaurant " displayed above the jokes list
- [ ] Link at top-left corner links to last page
- [ ] Shows one photo of each restaurant 
- [ ] The name, Cuisine and Rating are displayed below the photo. they and photo should be in on card
- [ ] The list is scrollable

## Tasks
- [ ] Create a branch
- [ ] Global styled
- [ ] Create "db.js" with Restaurants
- [ ] Save the photos in "images" folder and put it in "public" folder
- [ ] Create components/Card
- [ ] Create components/Nav
- [ ] Create components/Head
- [ ] Add page pages/restaurants
- [ ] Write tests

**Comment by salaos** [comment]
Good Work! 
The value proposition is little bit unclear, better: "As a user... I want to have a list of Restaurants ... in order to have an overview of the restaurants they want to choose from"

And what is the last page of "Link at top-left corner links to last page"?

**Comment by LuYujin9** [comment]
Thanks Nina. I update it. 

> And what is the last page of "Link at top-left corner links to last page"?
I would like to show the page  where I was before. In this case, it's Homepage. I try to find a better way to describe.
