### ISSUE TITLE
Details of one restaurant

### ISSUE THREAD

**Issue by LuYujin9** [LuYujin9/Capstone-Project-Lecker-Map#5]
## Value Proposition
- As a user
- I want to details of one restaurant 
- in order to know more informations of each restaurant

## Description

![Image](https://user-images.githubusercontent.com/123362292/227511997-adeabccb-89e0-4279-9f15-bd7290f94a1e.png)

## Acceptance criteria
- [ ] on screen 1: the photo of each restaurant should link to the detail page
- [ ] on screen 2: display a preview of menu ,a photo and comments 
- [ ] the head ist the name of this restaurant
- [ ] the page  is scrollable
- [ ] should be also set a bookmark button, it is fixed and toggles color
- [ ] a button on each comment can  expand or collapse the comment
- [ ] on screen 3: the button should toggle icon

## Tasks
- [ ] Update components/Detail
- [ ] Create components/CommentButton
- [ ] create page pages/restaurants/[id]
- [ ] Write tests
